// Code generated by github.com/schigh/slice/base/base.go. DO NOT EDIT.

package slice

import "sort"

// Int16 is the alias of []int16
type Int16 []int16

// Value returns the aliased []int16
func (slc Int16) Value() []int16 {
	return []int16(slc)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slc Int16) IndexOf(needle int16) int {
	for i := 0; i < len(slc); i++ {
		if needle == slc[i] {
			return i
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slc Int16) Contains(needle int16) bool {
	return slc.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slc Int16) SortAsc() Int16 {
	sort.SliceStable(slc, func(i, j int) bool {
		return slc[i] < slc[j]
	})

	return slc
}

// SortDesc will sort the slice in descending order
func (slc Int16) SortDesc() Int16 {
	sort.SliceStable(slc, func(i, j int) bool {
		return slc[j] < slc[i]
	})

	return slc
}

// Reverse will reverse the order of the slice
func (slc Int16) Reverse() Int16 {
	l := len(slc)
	for i, j := 0, l-1; i < l/2; i++ {
		slc[i], slc[j] = slc[j], slc[i]
		j--
	}

	return slc
}

// Unique filters out duplicate int16 values
func (slc Int16) Unique() Int16 {
	u := make([]int16, 0, len(slc))
	m := make(map[int16]bool)

	for i := 0; i < len(slc); i++ {
		if _, ok := m[slc[i]]; !ok {
			m[slc[i]] = true
			u = append(u, slc[i])
		}
	}

	return Int16(u)
}

// Filter will return all int16 values that evaluate true in the user-supplied function
func (slc Int16) Filter(f func(int16) bool) Int16 {
	out := make([]int16, 0, len(slc))
	for i := 0; i < len(slc); i++ {
		if f(slc[i]) {
			out = append(out, slc[i])
		}
	}

	return Int16(out)
}

// Each will apply a function to each int16 in the slice.
// This function will iterate over the slice completely.  No
// items in the slice should be mutated by this operation.
func (slc Int16) Each(f func(int16)) {
	for i := 0; i < len(slc); i++ {
		f(slc[i])
	}
}

// TryEach will apply a function to each int16 in the slice.
// If the function returns an error, the iteration will stop and return
// the index of the element that caused the function to return the error.
// The second returned value will be first error returned from the
// supplied function, and nil otherwise.
// No items in the slice should be mutated by this operation.
func (slc Int16) TryEach(f func(int16) error) (int, error) {
	for i := 0; i < len(slc); i++ {
		if err := f(slc[i]); err != nil {
			return i, err
		}
	}

	return NotInSlice, nil
}

// IfEach will apply a function to each int16 in the slice.
// If the function returns false, the iteration will stop and return
// the index of the element that caused the function to return false.
// The second returned value will be true if all members of the slice
// cause the provided function to return true, and false otherwise.
// No items in the slice should be mutated by this operation.
func (slc Int16) IfEach(f func(int16) bool) (int, bool) {
	for i := 0; i < len(slc); i++ {
		if !f(slc[i]) {
			return i, false
		}
	}

	return NotInSlice, true
}

// Map will apply a function to each int16 in the slice and replace the previous value
func (slc Int16) Map(f func(int16) int16) {
	for i := 0; i < len(slc); i++ {
		slc[i] = f(slc[i])
	}
}

// Chunk will divide the slice of int16 into smaller slices defined by chunk length
func (slc Int16) Chunk(size int) [][]int16 {
	l := len(slc)
	if l == 0 || size <= 0 {
		return make([][]int16, 0)
	}

	floor := l / size
	out := make([][]int16, 0, floor+1)
	var k int

	for i := 0; i < floor; i++ {
		k = i*size + size
		out = append(out, slc[i*size:k])
	}
	if l > k {
		out = append(out, slc[k:])
	}

	return out
}
