// Code generated by github.com/schigh/slice/base/base.go. DO NOT EDIT.
package slice

import (
	"errors"
	"reflect"
	"sync/atomic"
	"testing"
)

func TestInt8_IndexOf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int8
		needle   int8
		expected int
	}{
		{
			name:     "only item",
			slc:      []int8{1},
			needle:   1,
			expected: 0,
		},
		{
			name:     "at index 1",
			slc:      []int8{0, 1, 1},
			needle:   1,
			expected: 1,
		},
		{
			name:     "missing",
			slc:      []int8{1, 2, 3, 4},
			needle:   5,
			expected: NotInSlice,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int8(tt.slc).IndexOf(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %d, got %d", tt.expected, result)
			}
		})
	}
}

func TestInt8_Contains(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int8
		needle   int8
		expected bool
	}{
		{
			name:     "present",
			slc:      []int8{1, 2, 3, 4},
			needle:   4,
			expected: true,
		},
		{
			name:     "not present",
			slc:      []int8{1, 2, 3, 4},
			needle:   5,
			expected: false,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int8(tt.slc).Contains(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt8_SortAsc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int8
		expected []int8
	}{
		{
			name:     "empty",
			slc:      []int8{},
			expected: []int8{},
		},
		{
			name:     "already sorted",
			slc:      []int8{0, 1, 2, 3, 4, 5},
			expected: []int8{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "reversed",
			slc:      []int8{5, 4, 3, 2, 1, 0},
			expected: []int8{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "random",
			slc:      []int8{3, 1, 4, 5, 0, 2},
			expected: []int8{0, 1, 2, 3, 4, 5},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int8(tt.slc).SortAsc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt8_SortDesc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int8
		expected []int8
	}{
		{
			name:     "empty",
			slc:      []int8{},
			expected: []int8{},
		},
		{
			name:     "already sorted",
			slc:      []int8{5, 4, 3, 2, 1, 0},
			expected: []int8{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "reversed",
			slc:      []int8{0, 1, 2, 3, 4, 5},
			expected: []int8{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "random",
			slc:      []int8{3, 1, 4, 5, 0, 2},
			expected: []int8{5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int8(tt.slc).SortDesc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt8_Unique(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int8
		expected []int8
	}{
		{
			name:     "unaffected",
			slc:      []int8{0, 1, 2, 3, 4, 5},
			expected: []int8{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "one extra five",
			slc:      []int8{5, 0, 1, 2, 3, 4, 5},
			expected: []int8{5, 0, 1, 2, 3, 4},
		},
		{
			name:     "extras everywhere",
			slc:      []int8{0, 0, 1, 0, 1, 2, 2, 2, 3, 0, 3, 4, 2, 3, 4, 4, 2, 1, 0},
			expected: []int8{0, 1, 2, 3, 4},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int8(tt.slc).Unique().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt8_Reverse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int8
		expected []int8
	}{
		{
			name:     "even length",
			slc:      []int8{0, 1, 2, 3, 4, 5},
			expected: []int8{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "odd length",
			slc:      []int8{0, 1, 2, 3, 4, 5, 6},
			expected: []int8{6, 5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int8(tt.slc).Reverse().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt8_Filter(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		slc        []int8
		expected   []int8
		filterFunc func(int8) bool
	}{
		{
			name:       "gt 10",
			slc:        []int8{1, 2, 5, 11, 13, 15},
			expected:   []int8{11, 13, 15},
			filterFunc: func(n int8) bool { return n > 10 },
		},
		{
			name:       "mod 3",
			slc:        []int8{1, 2, 6, 11, 12, 15, 17},
			expected:   []int8{6, 12, 15},
			filterFunc: func(n int8) bool { return n%3 == 0 },
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int8(tt.slc).Filter(tt.filterFunc).Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt8_Each(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(int8(0))

	tests := []struct {
		name     string
		slc      []int8
		expected int8
		eachFunc func(int8)
	}{
		{
			name:     "add n",
			slc:      []int8{1, 2, 5, 11, 13, 15},
			expected: 47,
			eachFunc: func(n int8) {
				v := rabbit.Load().(int8)
				v = v + n
				rabbit.Store(v)
			},
		},
		{
			name:     "subtract n",
			slc:      []int8{1, 2, 6, 8, 12},
			expected: 18,
			eachFunc: func(n int8) {
				v := rabbit.Load().(int8)
				v = v - n
				rabbit.Store(v)
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			Int8(tt.slc).Each(tt.eachFunc)
			v := rabbit.Load().(int8)
			if tt.expected != v {
				t.Errorf("expected %v, got %v", tt.expected, rabbit)
			}
		})
	}
}

func TestInt8_TryEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(int8(0))

	myErr := errors.New("i am an error")
	tests := []struct {
		name      string
		slc       []int8
		expected  int
		expected2 error
		before    func()
		eachFunc  func(int8) error
	}{
		{
			name:      "add n",
			slc:       []int8{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n int8) error {
				v := rabbit.Load().(int8)
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "subtract n",
			slc:       []int8{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n int8) error {
				v := rabbit.Load().(int8)
				v = v - n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "errors",
			slc:       []int8{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: myErr,
			before:    func() { rabbit.Store(int8(0)) },
			eachFunc: func(n int8) error {
				v := rabbit.Load().(int8)
				if n > 5 {
					return myErr
				}
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := Int8(tt.slc).TryEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestInt8_IfEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(int8(0))

	tests := []struct {
		name      string
		slc       []int8
		expected  int
		expected2 bool
		before    func()
		err       error
		eachFunc  func(int8) bool
	}{
		{
			name:      "all return true",
			slc:       []int8{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n int8) bool {
				v := rabbit.Load().(int8)
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "subtract n",
			slc:       []int8{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n int8) bool {
				v := rabbit.Load().(int8)
				v = v - n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "breaking",
			slc:       []int8{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: false,
			before:    func() { rabbit.Store(int8(0)) },
			eachFunc: func(n int8) bool {
				v := rabbit.Load().(int8)
				if n > 5 {
					return false
				}
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := Int8(tt.slc).IfEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestInt8_Map(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int8
		expected []int8
		mapFunc  func(int8) int8
	}{
		{
			name:     "add 3",
			slc:      []int8{1, 2, 5, 11, 13, 15},
			expected: []int8{4, 5, 8, 14, 16, 18},
			mapFunc:  func(n int8) int8 { return n + 3 },
		},
		{
			name:     "set mod 2",
			slc:      []int8{1, 2, 6, 8, 12, 15, 17},
			expected: []int8{1, 0, 0, 0, 0, 1, 1},
			mapFunc:  func(n int8) int8 { return int8(n % 2) },
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			Int8(tt.slc).Map(tt.mapFunc)
			if !reflect.DeepEqual(tt.expected, tt.slc) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func TestInt8_Chunk(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		size     int
		slc      []int8
		expected [][]int8
	}{
		{
			name:     "chunks of 2 no remainder",
			size:     2,
			slc:      []int8{1, 2, 5, 11, 13, 15},
			expected: [][]int8{[]int8{1, 2}, []int8{5, 11}, []int8{13, 15}},
		},
		{
			name:     "chunks of 2 with remainder",
			size:     2,
			slc:      []int8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int8{[]int8{1, 2}, []int8{5, 11}, []int8{13, 15}, []int8{17}},
		},
		{
			name:     "chunks of 100",
			size:     100,
			slc:      []int8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int8{[]int8{1, 2, 5, 11, 13, 15, 17}},
		},
		{
			name:     "chunks of 4",
			size:     4,
			slc:      []int8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int8{[]int8{1, 2, 5, 11}, []int8{13, 15, 17}},
		},
		{
			name:     "chunks of 5",
			size:     5,
			slc:      []int8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int8{[]int8{1, 2, 5, 11, 13}, []int8{15, 17}},
		},
		{
			name:     "empty slice",
			size:     5,
			slc:      []int8{},
			expected: [][]int8{},
		},
		{
			name:     "invalid chunk size",
			size:     -1,
			slc:      []int8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int8{},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			out := Int8(tt.slc).Chunk(tt.size)
			if !reflect.DeepEqual(tt.expected, out) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func BenchmarkInt8_IndexOf(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).IndexOf(1)
			}
		})
	}
}

func BenchmarkInt8_Contains(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).Contains(1)
			}
		})
	}
}

func BenchmarkInt8_SortAsc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).SortAsc()
			}
		})
	}
}

func BenchmarkInt8_SortDesc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).SortDesc()
			}
		})
	}
}

func BenchmarkInt8_Reverse(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).Reverse()
			}
		})
	}
}

func BenchmarkInt8_Filter(b *testing.B) {
	benchFunc := func(n int8) bool {
		return true
	}
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).Filter(benchFunc)
			}
		})
	}
}

func BenchmarkInt8_Each(b *testing.B) {
	benchFunc := func(n int8) { n = 0 }
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).Each(benchFunc)
			}
		})
	}
}

func BenchmarkInt8_Map(b *testing.B) {
	benchFunc := func(n int8) int8 {
		return n
	}
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).Map(benchFunc)
			}
		})
	}
}

func BenchmarkInt8_Unique(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int8
	}{
		{
			name: "10 elements",
			slc:  genInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int8(bm.slc).Unique()
			}
		})
	}
}
