// Code generated by github.com/schigh/slice/base/base.go. DO NOT EDIT.
package slice

import (
	"errors"
	"reflect"
	"sync/atomic"
	"testing"
)

func TestInt_IndexOf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int
		needle   int
		expected int
	}{
		{
			name:     "only item",
			slc:      []int{1},
			needle:   1,
			expected: 0,
		},
		{
			name:     "at index 1",
			slc:      []int{0, 1, 1},
			needle:   1,
			expected: 1,
		},
		{
			name:     "missing",
			slc:      []int{1, 2, 3, 4},
			needle:   5,
			expected: NotInSlice,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int(tt.slc).IndexOf(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %d, got %d", tt.expected, result)
			}
		})
	}
}

func TestInt_Contains(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int
		needle   int
		expected bool
	}{
		{
			name:     "present",
			slc:      []int{1, 2, 3, 4},
			needle:   4,
			expected: true,
		},
		{
			name:     "not present",
			slc:      []int{1, 2, 3, 4},
			needle:   5,
			expected: false,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int(tt.slc).Contains(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt_SortAsc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int
		expected []int
	}{
		{
			name:     "empty",
			slc:      []int{},
			expected: []int{},
		},
		{
			name:     "already sorted",
			slc:      []int{0, 1, 2, 3, 4, 5},
			expected: []int{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "reversed",
			slc:      []int{5, 4, 3, 2, 1, 0},
			expected: []int{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "random",
			slc:      []int{3, 1, 4, 5, 0, 2},
			expected: []int{0, 1, 2, 3, 4, 5},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int(tt.slc).SortAsc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt_SortDesc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int
		expected []int
	}{
		{
			name:     "empty",
			slc:      []int{},
			expected: []int{},
		},
		{
			name:     "already sorted",
			slc:      []int{5, 4, 3, 2, 1, 0},
			expected: []int{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "reversed",
			slc:      []int{0, 1, 2, 3, 4, 5},
			expected: []int{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "random",
			slc:      []int{3, 1, 4, 5, 0, 2},
			expected: []int{5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int(tt.slc).SortDesc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt_Unique(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int
		expected []int
	}{
		{
			name:     "unaffected",
			slc:      []int{0, 1, 2, 3, 4, 5},
			expected: []int{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "one extra five",
			slc:      []int{5, 0, 1, 2, 3, 4, 5},
			expected: []int{5, 0, 1, 2, 3, 4},
		},
		{
			name:     "extras everywhere",
			slc:      []int{0, 0, 1, 0, 1, 2, 2, 2, 3, 0, 3, 4, 2, 3, 4, 4, 2, 1, 0},
			expected: []int{0, 1, 2, 3, 4},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int(tt.slc).Unique().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt_Reverse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int
		expected []int
	}{
		{
			name:     "even length",
			slc:      []int{0, 1, 2, 3, 4, 5},
			expected: []int{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "odd length",
			slc:      []int{0, 1, 2, 3, 4, 5, 6},
			expected: []int{6, 5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int(tt.slc).Reverse().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt_Filter(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		slc        []int
		expected   []int
		filterFunc func(int) bool
	}{
		{
			name:       "gt 10",
			slc:        []int{1, 2, 5, 11, 13, 15},
			expected:   []int{11, 13, 15},
			filterFunc: func(n int) bool { return n > 10 },
		},
		{
			name:       "mod 3",
			slc:        []int{1, 2, 6, 11, 12, 15, 17},
			expected:   []int{6, 12, 15},
			filterFunc: func(n int) bool { return n%3 == 0 },
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := Int(tt.slc).Filter(tt.filterFunc).Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestInt_Each(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(int(0))

	tests := []struct {
		name     string
		slc      []int
		expected int
		eachFunc func(int)
	}{
		{
			name:     "add n",
			slc:      []int{1, 2, 5, 11, 13, 15},
			expected: 47,
			eachFunc: func(n int) {
				v := rabbit.Load().(int)
				v = v + n
				rabbit.Store(v)
			},
		},
		{
			name:     "subtract n",
			slc:      []int{1, 2, 6, 8, 12},
			expected: 18,
			eachFunc: func(n int) {
				v := rabbit.Load().(int)
				v = v - n
				rabbit.Store(v)
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			Int(tt.slc).Each(tt.eachFunc)
			v := rabbit.Load().(int)
			if tt.expected != v {
				t.Errorf("expected %v, got %v", tt.expected, rabbit)
			}
		})
	}
}

func TestInt_TryEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(int(0))

	myErr := errors.New("i am an error")
	tests := []struct {
		name      string
		slc       []int
		expected  int
		expected2 error
		before    func()
		eachFunc  func(int) error
	}{
		{
			name:      "add n",
			slc:       []int{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n int) error {
				v := rabbit.Load().(int)
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "subtract n",
			slc:       []int{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n int) error {
				v := rabbit.Load().(int)
				v = v - n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "errors",
			slc:       []int{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: myErr,
			before:    func() { rabbit.Store(int(0)) },
			eachFunc: func(n int) error {
				v := rabbit.Load().(int)
				if n > 5 {
					return myErr
				}
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := Int(tt.slc).TryEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestInt_IfEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(int(0))

	tests := []struct {
		name      string
		slc       []int
		expected  int
		expected2 bool
		before    func()
		err       error
		eachFunc  func(int) bool
	}{
		{
			name:      "all return true",
			slc:       []int{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n int) bool {
				v := rabbit.Load().(int)
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "subtract n",
			slc:       []int{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n int) bool {
				v := rabbit.Load().(int)
				v = v - n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "breaking",
			slc:       []int{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: false,
			before:    func() { rabbit.Store(int(0)) },
			eachFunc: func(n int) bool {
				v := rabbit.Load().(int)
				if n > 5 {
					return false
				}
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := Int(tt.slc).IfEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestInt_Map(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []int
		expected []int
		mapFunc  func(int) int
	}{
		{
			name:     "add 3",
			slc:      []int{1, 2, 5, 11, 13, 15},
			expected: []int{4, 5, 8, 14, 16, 18},
			mapFunc:  func(n int) int { return n + 3 },
		},
		{
			name:     "set mod 2",
			slc:      []int{1, 2, 6, 8, 12, 15, 17},
			expected: []int{1, 0, 0, 0, 0, 1, 1},
			mapFunc:  func(n int) int { return int(n % 2) },
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			Int(tt.slc).Map(tt.mapFunc)
			if !reflect.DeepEqual(tt.expected, tt.slc) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func TestInt_Chunk(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		size     int
		slc      []int
		expected [][]int
	}{
		{
			name:     "chunks of 2 no remainder",
			size:     2,
			slc:      []int{1, 2, 5, 11, 13, 15},
			expected: [][]int{[]int{1, 2}, []int{5, 11}, []int{13, 15}},
		},
		{
			name:     "chunks of 2 with remainder",
			size:     2,
			slc:      []int{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int{[]int{1, 2}, []int{5, 11}, []int{13, 15}, []int{17}},
		},
		{
			name:     "chunks of 100",
			size:     100,
			slc:      []int{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int{[]int{1, 2, 5, 11, 13, 15, 17}},
		},
		{
			name:     "chunks of 4",
			size:     4,
			slc:      []int{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int{[]int{1, 2, 5, 11}, []int{13, 15, 17}},
		},
		{
			name:     "chunks of 5",
			size:     5,
			slc:      []int{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int{[]int{1, 2, 5, 11, 13}, []int{15, 17}},
		},
		{
			name:     "empty slice",
			size:     5,
			slc:      []int{},
			expected: [][]int{},
		},
		{
			name:     "invalid chunk size",
			size:     -1,
			slc:      []int{1, 2, 5, 11, 13, 15, 17},
			expected: [][]int{},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			out := Int(tt.slc).Chunk(tt.size)
			if !reflect.DeepEqual(tt.expected, out) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func BenchmarkInt_IndexOf(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).IndexOf(1)
			}
		})
	}
}

func BenchmarkInt_Contains(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).Contains(1)
			}
		})
	}
}

func BenchmarkInt_SortAsc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).SortAsc()
			}
		})
	}
}

func BenchmarkInt_SortDesc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).SortDesc()
			}
		})
	}
}

func BenchmarkInt_Reverse(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).Reverse()
			}
		})
	}
}

func BenchmarkInt_Filter(b *testing.B) {
	benchFunc := func(n int) bool {
		return true
	}
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).Filter(benchFunc)
			}
		})
	}
}

func BenchmarkInt_Each(b *testing.B) {
	benchFunc := func(n int) { n = 0 }
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).Each(benchFunc)
			}
		})
	}
}

func BenchmarkInt_Map(b *testing.B) {
	benchFunc := func(n int) int {
		return n
	}
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).Map(benchFunc)
			}
		})
	}
}

func BenchmarkInt_Unique(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []int
	}{
		{
			name: "10 elements",
			slc:  genInt(b, 10),
		},
		{
			name: "100 elements",
			slc:  genInt(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genInt(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genInt(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genInt(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				Int(bm.slc).Unique()
			}
		})
	}
}
