// Code generated by github.com/schigh/slice/base/base.go. DO NOT EDIT.
package slice

import (
	"errors"
	"reflect"
	"sync/atomic"
	"testing"
)

func TestUInt16_IndexOf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint16
		needle   uint16
		expected int
	}{
		{
			name:     "only item",
			slc:      []uint16{1},
			needle:   1,
			expected: 0,
		},
		{
			name:     "at index 1",
			slc:      []uint16{0, 1, 1},
			needle:   1,
			expected: 1,
		},
		{
			name:     "missing",
			slc:      []uint16{1, 2, 3, 4},
			needle:   5,
			expected: NotInSlice,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt16(tt.slc).IndexOf(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %d, got %d", tt.expected, result)
			}
		})
	}
}

func TestUInt16_Contains(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint16
		needle   uint16
		expected bool
	}{
		{
			name:     "present",
			slc:      []uint16{1, 2, 3, 4},
			needle:   4,
			expected: true,
		},
		{
			name:     "not present",
			slc:      []uint16{1, 2, 3, 4},
			needle:   5,
			expected: false,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt16(tt.slc).Contains(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt16_SortAsc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint16
		expected []uint16
	}{
		{
			name:     "empty",
			slc:      []uint16{},
			expected: []uint16{},
		},
		{
			name:     "already sorted",
			slc:      []uint16{0, 1, 2, 3, 4, 5},
			expected: []uint16{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "reversed",
			slc:      []uint16{5, 4, 3, 2, 1, 0},
			expected: []uint16{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "random",
			slc:      []uint16{3, 1, 4, 5, 0, 2},
			expected: []uint16{0, 1, 2, 3, 4, 5},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt16(tt.slc).SortAsc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt16_SortDesc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint16
		expected []uint16
	}{
		{
			name:     "empty",
			slc:      []uint16{},
			expected: []uint16{},
		},
		{
			name:     "already sorted",
			slc:      []uint16{5, 4, 3, 2, 1, 0},
			expected: []uint16{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "reversed",
			slc:      []uint16{0, 1, 2, 3, 4, 5},
			expected: []uint16{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "random",
			slc:      []uint16{3, 1, 4, 5, 0, 2},
			expected: []uint16{5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt16(tt.slc).SortDesc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt16_Unique(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint16
		expected []uint16
	}{
		{
			name:     "unaffected",
			slc:      []uint16{0, 1, 2, 3, 4, 5},
			expected: []uint16{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "one extra five",
			slc:      []uint16{5, 0, 1, 2, 3, 4, 5},
			expected: []uint16{5, 0, 1, 2, 3, 4},
		},
		{
			name:     "extras everywhere",
			slc:      []uint16{0, 0, 1, 0, 1, 2, 2, 2, 3, 0, 3, 4, 2, 3, 4, 4, 2, 1, 0},
			expected: []uint16{0, 1, 2, 3, 4},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt16(tt.slc).Unique().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt16_Reverse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint16
		expected []uint16
	}{
		{
			name:     "even length",
			slc:      []uint16{0, 1, 2, 3, 4, 5},
			expected: []uint16{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "odd length",
			slc:      []uint16{0, 1, 2, 3, 4, 5, 6},
			expected: []uint16{6, 5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt16(tt.slc).Reverse().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt16_Filter(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		slc        []uint16
		expected   []uint16
		filterFunc func(uint16) bool
	}{
		{
			name:       "gt 10",
			slc:        []uint16{1, 2, 5, 11, 13, 15},
			expected:   []uint16{11, 13, 15},
			filterFunc: func(n uint16) bool { return n > 10 },
		},
		{
			name:       "mod 3",
			slc:        []uint16{1, 2, 6, 11, 12, 15, 17},
			expected:   []uint16{6, 12, 15},
			filterFunc: func(n uint16) bool { return n%3 == 0 },
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt16(tt.slc).Filter(tt.filterFunc).Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt16_Each(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(uint16(0))

	tests := []struct {
		name     string
		slc      []uint16
		expected uint16
		eachFunc func(uint16)
	}{
		{
			name:     "add n",
			slc:      []uint16{1, 2, 5, 11, 13, 15},
			expected: 47,
			eachFunc: func(n uint16) {
				v := rabbit.Load().(uint16)
				v = v + n
				rabbit.Store(v)
			},
		},
		{
			name:     "subtract n",
			slc:      []uint16{1, 2, 6, 8, 12},
			expected: 18,
			eachFunc: func(n uint16) {
				v := rabbit.Load().(uint16)
				v = v - n
				rabbit.Store(v)
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			UInt16(tt.slc).Each(tt.eachFunc)
			v := rabbit.Load().(uint16)
			if tt.expected != v {
				t.Errorf("expected %v, got %v", tt.expected, rabbit)
			}
		})
	}
}

func TestUInt16_TryEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(uint16(0))

	myErr := errors.New("i am an error")
	tests := []struct {
		name      string
		slc       []uint16
		expected  int
		expected2 error
		before    func()
		eachFunc  func(uint16) error
	}{
		{
			name:      "add n",
			slc:       []uint16{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n uint16) error {
				v := rabbit.Load().(uint16)
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "subtract n",
			slc:       []uint16{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n uint16) error {
				v := rabbit.Load().(uint16)
				v = v - n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "errors",
			slc:       []uint16{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: myErr,
			before:    func() { rabbit.Store(uint16(0)) },
			eachFunc: func(n uint16) error {
				v := rabbit.Load().(uint16)
				if n > 5 {
					return myErr
				}
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := UInt16(tt.slc).TryEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestUInt16_IfEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(uint16(0))

	tests := []struct {
		name      string
		slc       []uint16
		expected  int
		expected2 bool
		before    func()
		err       error
		eachFunc  func(uint16) bool
	}{
		{
			name:      "all return true",
			slc:       []uint16{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n uint16) bool {
				v := rabbit.Load().(uint16)
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "subtract n",
			slc:       []uint16{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n uint16) bool {
				v := rabbit.Load().(uint16)
				v = v - n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "breaking",
			slc:       []uint16{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: false,
			before:    func() { rabbit.Store(uint16(0)) },
			eachFunc: func(n uint16) bool {
				v := rabbit.Load().(uint16)
				if n > 5 {
					return false
				}
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := UInt16(tt.slc).IfEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestUInt16_Map(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint16
		expected []uint16
		mapFunc  func(uint16) uint16
	}{
		{
			name:     "add 3",
			slc:      []uint16{1, 2, 5, 11, 13, 15},
			expected: []uint16{4, 5, 8, 14, 16, 18},
			mapFunc:  func(n uint16) uint16 { return n + 3 },
		},
		{
			name:     "set mod 2",
			slc:      []uint16{1, 2, 6, 8, 12, 15, 17},
			expected: []uint16{1, 0, 0, 0, 0, 1, 1},
			mapFunc:  func(n uint16) uint16 { return uint16(n % 2) },
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			UInt16(tt.slc).Map(tt.mapFunc)
			if !reflect.DeepEqual(tt.expected, tt.slc) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func TestUInt16_Chunk(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		size     int
		slc      []uint16
		expected [][]uint16
	}{
		{
			name:     "chunks of 2 no remainder",
			size:     2,
			slc:      []uint16{1, 2, 5, 11, 13, 15},
			expected: [][]uint16{[]uint16{1, 2}, []uint16{5, 11}, []uint16{13, 15}},
		},
		{
			name:     "chunks of 2 with remainder",
			size:     2,
			slc:      []uint16{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint16{[]uint16{1, 2}, []uint16{5, 11}, []uint16{13, 15}, []uint16{17}},
		},
		{
			name:     "chunks of 100",
			size:     100,
			slc:      []uint16{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint16{[]uint16{1, 2, 5, 11, 13, 15, 17}},
		},
		{
			name:     "chunks of 4",
			size:     4,
			slc:      []uint16{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint16{[]uint16{1, 2, 5, 11}, []uint16{13, 15, 17}},
		},
		{
			name:     "chunks of 5",
			size:     5,
			slc:      []uint16{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint16{[]uint16{1, 2, 5, 11, 13}, []uint16{15, 17}},
		},
		{
			name:     "empty slice",
			size:     5,
			slc:      []uint16{},
			expected: [][]uint16{},
		},
		{
			name:     "invalid chunk size",
			size:     -1,
			slc:      []uint16{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint16{},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			out := UInt16(tt.slc).Chunk(tt.size)
			if !reflect.DeepEqual(tt.expected, out) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func BenchmarkUInt16_IndexOf(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).IndexOf(1)
			}
		})
	}
}

func BenchmarkUInt16_Contains(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).Contains(1)
			}
		})
	}
}

func BenchmarkUInt16_SortAsc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).SortAsc()
			}
		})
	}
}

func BenchmarkUInt16_SortDesc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).SortDesc()
			}
		})
	}
}

func BenchmarkUInt16_Reverse(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).Reverse()
			}
		})
	}
}

func BenchmarkUInt16_Filter(b *testing.B) {
	benchFunc := func(n uint16) bool {
		return true
	}
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).Filter(benchFunc)
			}
		})
	}
}

func BenchmarkUInt16_Each(b *testing.B) {
	benchFunc := func(n uint16) { n = 0 }
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).Each(benchFunc)
			}
		})
	}
}

func BenchmarkUInt16_Map(b *testing.B) {
	benchFunc := func(n uint16) uint16 {
		return n
	}
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).Map(benchFunc)
			}
		})
	}
}

func BenchmarkUInt16_Unique(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint16
	}{
		{
			name: "10 elements",
			slc:  genUInt16(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt16(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt16(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt16(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt16(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt16(bm.slc).Unique()
			}
		})
	}
}
