// Code generated by github.com/schigh/slice/base/base.go. DO NOT EDIT.
package slice

import (
	"errors"
	"reflect"
	"sync/atomic"
	"testing"
)

func TestUInt8_IndexOf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint8
		needle   uint8
		expected int
	}{
		{
			name:     "only item",
			slc:      []uint8{1},
			needle:   1,
			expected: 0,
		},
		{
			name:     "at index 1",
			slc:      []uint8{0, 1, 1},
			needle:   1,
			expected: 1,
		},
		{
			name:     "missing",
			slc:      []uint8{1, 2, 3, 4},
			needle:   5,
			expected: NotInSlice,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt8(tt.slc).IndexOf(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %d, got %d", tt.expected, result)
			}
		})
	}
}

func TestUInt8_Contains(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint8
		needle   uint8
		expected bool
	}{
		{
			name:     "present",
			slc:      []uint8{1, 2, 3, 4},
			needle:   4,
			expected: true,
		},
		{
			name:     "not present",
			slc:      []uint8{1, 2, 3, 4},
			needle:   5,
			expected: false,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt8(tt.slc).Contains(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt8_SortAsc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint8
		expected []uint8
	}{
		{
			name:     "empty",
			slc:      []uint8{},
			expected: []uint8{},
		},
		{
			name:     "already sorted",
			slc:      []uint8{0, 1, 2, 3, 4, 5},
			expected: []uint8{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "reversed",
			slc:      []uint8{5, 4, 3, 2, 1, 0},
			expected: []uint8{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "random",
			slc:      []uint8{3, 1, 4, 5, 0, 2},
			expected: []uint8{0, 1, 2, 3, 4, 5},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt8(tt.slc).SortAsc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt8_SortDesc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint8
		expected []uint8
	}{
		{
			name:     "empty",
			slc:      []uint8{},
			expected: []uint8{},
		},
		{
			name:     "already sorted",
			slc:      []uint8{5, 4, 3, 2, 1, 0},
			expected: []uint8{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "reversed",
			slc:      []uint8{0, 1, 2, 3, 4, 5},
			expected: []uint8{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "random",
			slc:      []uint8{3, 1, 4, 5, 0, 2},
			expected: []uint8{5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt8(tt.slc).SortDesc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt8_Unique(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint8
		expected []uint8
	}{
		{
			name:     "unaffected",
			slc:      []uint8{0, 1, 2, 3, 4, 5},
			expected: []uint8{0, 1, 2, 3, 4, 5},
		},
		{
			name:     "one extra five",
			slc:      []uint8{5, 0, 1, 2, 3, 4, 5},
			expected: []uint8{5, 0, 1, 2, 3, 4},
		},
		{
			name:     "extras everywhere",
			slc:      []uint8{0, 0, 1, 0, 1, 2, 2, 2, 3, 0, 3, 4, 2, 3, 4, 4, 2, 1, 0},
			expected: []uint8{0, 1, 2, 3, 4},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt8(tt.slc).Unique().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt8_Reverse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint8
		expected []uint8
	}{
		{
			name:     "even length",
			slc:      []uint8{0, 1, 2, 3, 4, 5},
			expected: []uint8{5, 4, 3, 2, 1, 0},
		},
		{
			name:     "odd length",
			slc:      []uint8{0, 1, 2, 3, 4, 5, 6},
			expected: []uint8{6, 5, 4, 3, 2, 1, 0},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt8(tt.slc).Reverse().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt8_Filter(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		slc        []uint8
		expected   []uint8
		filterFunc func(uint8) bool
	}{
		{
			name:       "gt 10",
			slc:        []uint8{1, 2, 5, 11, 13, 15},
			expected:   []uint8{11, 13, 15},
			filterFunc: func(n uint8) bool { return n > 10 },
		},
		{
			name:       "mod 3",
			slc:        []uint8{1, 2, 6, 11, 12, 15, 17},
			expected:   []uint8{6, 12, 15},
			filterFunc: func(n uint8) bool { return n%3 == 0 },
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := UInt8(tt.slc).Filter(tt.filterFunc).Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestUInt8_Each(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(uint8(0))

	tests := []struct {
		name     string
		slc      []uint8
		expected uint8
		eachFunc func(uint8)
	}{
		{
			name:     "add n",
			slc:      []uint8{1, 2, 5, 11, 13, 15},
			expected: 47,
			eachFunc: func(n uint8) {
				v := rabbit.Load().(uint8)
				v = v + n
				rabbit.Store(v)
			},
		},
		{
			name:     "subtract n",
			slc:      []uint8{1, 2, 6, 8, 12},
			expected: 18,
			eachFunc: func(n uint8) {
				v := rabbit.Load().(uint8)
				v = v - n
				rabbit.Store(v)
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			UInt8(tt.slc).Each(tt.eachFunc)
			v := rabbit.Load().(uint8)
			if tt.expected != v {
				t.Errorf("expected %v, got %v", tt.expected, rabbit)
			}
		})
	}
}

func TestUInt8_TryEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(uint8(0))

	myErr := errors.New("i am an error")
	tests := []struct {
		name      string
		slc       []uint8
		expected  int
		expected2 error
		before    func()
		eachFunc  func(uint8) error
	}{
		{
			name:      "add n",
			slc:       []uint8{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n uint8) error {
				v := rabbit.Load().(uint8)
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "subtract n",
			slc:       []uint8{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: nil,
			eachFunc: func(n uint8) error {
				v := rabbit.Load().(uint8)
				v = v - n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name:      "errors",
			slc:       []uint8{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: myErr,
			before:    func() { rabbit.Store(uint8(0)) },
			eachFunc: func(n uint8) error {
				v := rabbit.Load().(uint8)
				if n > 5 {
					return myErr
				}
				v = v + n
				rabbit.Store(v)
				return nil
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := UInt8(tt.slc).TryEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestUInt8_IfEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store(uint8(0))

	tests := []struct {
		name      string
		slc       []uint8
		expected  int
		expected2 bool
		before    func()
		err       error
		eachFunc  func(uint8) bool
	}{
		{
			name:      "all return true",
			slc:       []uint8{1, 2, 5, 11, 13, 15},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n uint8) bool {
				v := rabbit.Load().(uint8)
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "subtract n",
			slc:       []uint8{1, 2, 6, 8, 12},
			expected:  NotInSlice,
			expected2: true,
			eachFunc: func(n uint8) bool {
				v := rabbit.Load().(uint8)
				v = v - n
				rabbit.Store(v)
				return true
			},
		},
		{
			name:      "breaking",
			slc:       []uint8{1, 2, 5, 11, 13, 15},
			expected:  3,
			expected2: false,
			before:    func() { rabbit.Store(uint8(0)) },
			eachFunc: func(n uint8) bool {
				v := rabbit.Load().(uint8)
				if n > 5 {
					return false
				}
				v = v + n
				rabbit.Store(v)
				return true
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := UInt8(tt.slc).IfEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func TestUInt8_Map(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		slc      []uint8
		expected []uint8
		mapFunc  func(uint8) uint8
	}{
		{
			name:     "add 3",
			slc:      []uint8{1, 2, 5, 11, 13, 15},
			expected: []uint8{4, 5, 8, 14, 16, 18},
			mapFunc:  func(n uint8) uint8 { return n + 3 },
		},
		{
			name:     "set mod 2",
			slc:      []uint8{1, 2, 6, 8, 12, 15, 17},
			expected: []uint8{1, 0, 0, 0, 0, 1, 1},
			mapFunc:  func(n uint8) uint8 { return uint8(n % 2) },
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			UInt8(tt.slc).Map(tt.mapFunc)
			if !reflect.DeepEqual(tt.expected, tt.slc) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func TestUInt8_Chunk(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		size     int
		slc      []uint8
		expected [][]uint8
	}{
		{
			name:     "chunks of 2 no remainder",
			size:     2,
			slc:      []uint8{1, 2, 5, 11, 13, 15},
			expected: [][]uint8{[]uint8{1, 2}, []uint8{5, 11}, []uint8{13, 15}},
		},
		{
			name:     "chunks of 2 with remainder",
			size:     2,
			slc:      []uint8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint8{[]uint8{1, 2}, []uint8{5, 11}, []uint8{13, 15}, []uint8{17}},
		},
		{
			name:     "chunks of 100",
			size:     100,
			slc:      []uint8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint8{[]uint8{1, 2, 5, 11, 13, 15, 17}},
		},
		{
			name:     "chunks of 4",
			size:     4,
			slc:      []uint8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint8{[]uint8{1, 2, 5, 11}, []uint8{13, 15, 17}},
		},
		{
			name:     "chunks of 5",
			size:     5,
			slc:      []uint8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint8{[]uint8{1, 2, 5, 11, 13}, []uint8{15, 17}},
		},
		{
			name:     "empty slice",
			size:     5,
			slc:      []uint8{},
			expected: [][]uint8{},
		},
		{
			name:     "invalid chunk size",
			size:     -1,
			slc:      []uint8{1, 2, 5, 11, 13, 15, 17},
			expected: [][]uint8{},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			out := UInt8(tt.slc).Chunk(tt.size)
			if !reflect.DeepEqual(tt.expected, out) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func BenchmarkUInt8_IndexOf(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).IndexOf(1)
			}
		})
	}
}

func BenchmarkUInt8_Contains(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).Contains(1)
			}
		})
	}
}

func BenchmarkUInt8_SortAsc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).SortAsc()
			}
		})
	}
}

func BenchmarkUInt8_SortDesc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).SortDesc()
			}
		})
	}
}

func BenchmarkUInt8_Reverse(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).Reverse()
			}
		})
	}
}

func BenchmarkUInt8_Filter(b *testing.B) {
	benchFunc := func(n uint8) bool {
		return true
	}
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).Filter(benchFunc)
			}
		})
	}
}

func BenchmarkUInt8_Each(b *testing.B) {
	benchFunc := func(n uint8) { n = 0 }
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).Each(benchFunc)
			}
		})
	}
}

func BenchmarkUInt8_Map(b *testing.B) {
	benchFunc := func(n uint8) uint8 {
		return n
	}
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).Map(benchFunc)
			}
		})
	}
}

func BenchmarkUInt8_Unique(b *testing.B) {
	benchmarks := []struct {
		name string
		slc  []uint8
	}{
		{
			name: "10 elements",
			slc:  genUInt8(b, 10),
		},
		{
			name: "100 elements",
			slc:  genUInt8(b, 100),
		},
		{
			name: "1000 elements",
			slc:  genUInt8(b, 1000),
		},
		{
			name: "10000 elements",
			slc:  genUInt8(b, 10000),
		},
		{
			name: "100000 elements",
			slc:  genUInt8(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt8(bm.slc).Unique()
			}
		})
	}
}
