// Code generated by github.com/schigh/slice/base/base.go. DO NOT EDIT.
{{/*
	.BaseType
	-	the base go type (int, uint, etc)
	
	.PackageType
	-	the slice alias name (Int, Int16, etc)
	
*/}}
package slice

import "sort"

// {{.PackageType}} is the alias of []{{.BaseType}}
type {{.PackageType}} []{{.BaseType}}

// Value returns the aliased []{{.BaseType}}
func (slc {{.PackageType}}) Value() []{{.BaseType}} {
	return []{{.BaseType}}(slc)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slc {{.PackageType}}) IndexOf(needle {{.BaseType}}) int {
	for i := 0; i < len(slc); i++ {
		if needle == slc[i] {
			return i
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slc {{.PackageType}}) Contains(needle {{.BaseType}}) bool {
	return slc.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slc {{.PackageType}}) SortAsc() {{.PackageType}} {
	sort.SliceStable(slc, func(i, j int) bool {
		return slc[i] < slc[j]
	})

	return slc
}

// SortDesc will sort the slice in descending order
func (slc {{.PackageType}}) SortDesc() {{.PackageType}} {
	sort.SliceStable(slc, func(i, j int) bool {
		return slc[j] < slc[i]
	})

	return slc
}

// Reverse will reverse the order of the slice
func (slc {{.PackageType}}) Reverse() {{.PackageType}} {
	l := len(slc)
	for i, j := 0, l-1; i < l/2; i++ {
		slc[i], slc[j] = slc[j], slc[i]
		j--
	}

	return slc
}

// Unique filters out duplicate {{.BaseType}} values
func (slc {{.PackageType}}) Unique() {{.PackageType}} {
	u := make([]{{.BaseType}}, 0, len(slc))
	m := make(map[{{.BaseType}}]bool)

	for i := 0; i < len(slc); i++ {
		if _, ok := m[slc[i]]; !ok {
			m[slc[i]] = true
			u = append(u, slc[i])
		}
	}

	return {{.PackageType}}(u)
}

// Filter will return all {{.BaseType}} values that evaluate true in the user-supplied function
func (slc {{.PackageType}}) Filter(f func({{.BaseType}}) bool) {{.PackageType}} {
	out := make([]{{.BaseType}}, 0, len(slc))
	for i := 0; i < len(slc); i++ {
		if f(slc[i]) {
			out = append(out, slc[i])
		}
	}

	return {{.PackageType}}(out)
}

// Each will apply a function to each {{.BaseType}} in the slice.
// This function will iterate over the slice completely.  No
// items in the slice should be mutated by this operation.
func (slc {{.PackageType}}) Each(f func({{.BaseType}})) {
	for i := 0; i < len(slc); i++ {
		f(slc[i])
	}
}

// TryEach will apply a function to each {{.BaseType}} in the slice.
// If the function returns an error, the iteration will stop and return
// the index of the element that caused the function to return the error.
// The second returned value will be first error returned from the
// supplied function, and nil otherwise.
// No items in the slice should be mutated by this operation.
func (slc {{.PackageType}}) TryEach(f func({{.BaseType}}) error) (int, error) {
	for i := 0; i < len(slc); i++ {
		if err := f(slc[i]); err != nil {
			return i, err
		}
	}

	return NotInSlice, nil
}

// IfEach will apply a function to each {{.BaseType}} in the slice.
// If the function returns false, the iteration will stop and return
// the index of the element that caused the function to return false.
// The second returned value will be true if all members of the slice
// cause the provided function to return true, and false otherwise.
// No items in the slice should be mutated by this operation.
func (slc {{.PackageType}}) IfEach(f func({{.BaseType}}) bool) (int, bool) {
	for i := 0; i < len(slc); i++ {
		if !f(slc[i]) {
			return i, false
		}
	}

	return NotInSlice, true
}

// Map will apply a function to each {{.BaseType}} in the slice and replace the previous value
func (slc {{.PackageType}}) Map(f func({{.BaseType}}) {{.BaseType}}) {
	for i := 0; i < len(slc); i++ {
		slc[i] = f(slc[i])
	}
}

// Chunk will divide the slice of {{.BaseType}} into smaller slices defined by chunk length
func (slc {{.PackageType}}) Chunk(size int) [][]{{.BaseType}} {
	l := len(slc)
	if l == 0 || size <= 0 {
		return make([][]{{.BaseType}}, 0)
	}

	floor := l / size
	out := make([][]{{.BaseType}}, 0, floor+1)
	var k int

	for i := 0; i < floor; i++ {
		k = i*size + size
		out = append(out, slc[i*size:k])
	}
	if l > k {
		out = append(out, slc[k:])
	}

	return out
}
