// Code generated by github.com/schigh/slice/base/base.go. DO NOT EDIT.
{{/*
	.BaseType
	-	the base go type (int, uint, etc)

	.PackageType
	-	the slice alias name (Int, Int16, etc)

*/}}package slice

import (
	"errors"
	"reflect"
	"strings"
	"sync/atomic"
	"testing"
)

func Test{{.PackageType}}_IndexOf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		needle {{.BaseType}}
		expected int
	}{
		{
			name: "only item",
			slc: []{{.BaseType}}{"foo"},
			needle: "foo",
			expected: 0,
		},
		{
			name: "at index 1",
			slc: []{{.BaseType}}{"foo","bar","bar"},
			needle: "bar",
			expected: 1,
		},
		{
			name: "missing",
			slc: []{{.BaseType}}{"foo","bar","fizz","buzz"},
			needle: "baz",
			expected: NotInSlice,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := {{.PackageType}}(tt.slc).IndexOf(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %d, got %d", tt.expected, result)
			}
		})
	}
}

func Test{{.PackageType}}_Contains(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		needle {{.BaseType}}
		expected bool
	}{
		{
			name: "present",
			slc: []{{.BaseType}}{"foo","bar","fizz","buzz"},
			needle: "buzz",
			expected: true,
		},
		{
			name: "not present",
			slc: []{{.BaseType}}{"foo","bar","fizz","buzz"},
			needle: "baz",
			expected: false,
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := {{.PackageType}}(tt.slc).Contains(tt.needle)
			if result != tt.expected {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func Test{{.PackageType}}_SortAsc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected []{{.BaseType}}
	}{
		{
			name: "empty",
			slc: []{{.BaseType}}{},
			expected: []{{.BaseType}}{},
		},
		{
			name: "already sorted",
			slc: []{{.BaseType}}{"bar","baz","buzz","fizz","foo"},
			expected: []{{.BaseType}}{"bar","baz","buzz","fizz","foo"},
		},
		{
			name: "reversed",
			slc: []{{.BaseType}}{"foo","fizz","buzz","baz","bar"},
			expected: []{{.BaseType}}{"bar","baz","buzz","fizz","foo"},
		},
		{
			name: "random",
			slc: []{{.BaseType}}{"foo","bar","fizz","buzz","baz"},
			expected: []{{.BaseType}}{"bar","baz","buzz","fizz","foo"},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := {{.PackageType}}(tt.slc).SortAsc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func Test{{.PackageType}}_SortDesc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected []{{.BaseType}}
	}{
		{
			name: "empty",
			slc: []{{.BaseType}}{},
			expected: []{{.BaseType}}{},
		},
		{
			name: "already sorted",
			slc: []{{.BaseType}}{"foo","fizz","buzz","baz","bar"},
			expected: []{{.BaseType}}{"foo","fizz","buzz","baz","bar"},
		},
		{
			name: "reversed",
			slc: []{{.BaseType}}{"bar","baz","buzz","fizz","foo"},
			expected: []{{.BaseType}}{"foo","fizz","buzz","baz","bar"},
		},
		{
			name: "random",
			slc: []{{.BaseType}}{"foo","bar","fizz","buzz","baz"},
			expected: []{{.BaseType}}{"foo","fizz","buzz","baz","bar"},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := {{.PackageType}}(tt.slc).SortDesc().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func Test{{.PackageType}}_Unique(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected []{{.BaseType}}
	}{
		{
			name: "unaffected",
			slc: []{{.BaseType}}{"foo","bar","fizz","buzz","baz"},
			expected: []{{.BaseType}}{"foo","bar","fizz","buzz","baz"},
		},
		{
			name: "one extra buzz",
			slc: []{{.BaseType}}{"foo","bar","fizz","buzz","baz","buzz"},
			expected: []{{.BaseType}}{"foo","bar","fizz","buzz","baz"},
		},
		{
			name: "extras everywhere",
			slc: []{{.BaseType}}{"foo","foo","bar","foo","bar","fizz","fizz","fizz","buzz","foo","buzz","baz","fizz","buzz","baz","baz","fizz","bar","foo"},
			expected: []{{.BaseType}}{"foo","bar","fizz","buzz","baz"},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := {{.PackageType}}(tt.slc).Unique().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func Test{{.PackageType}}_Reverse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected []{{.BaseType}}
	}{
		{
			name: "even length",
			slc: []{{.BaseType}}{"foo","bar","baz","fizz","buzz"},
			expected: []{{.BaseType}}{"buzz","fizz","baz","bar","foo"},
		},
		{
			name: "odd length",
			slc: []{{.BaseType}}{"foo","bar","baz","fizz","buzz","herp"},
			expected: []{{.BaseType}}{"herp","buzz","fizz","baz","bar","foo"},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := {{.PackageType}}(tt.slc).Reverse().Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func Test{{.PackageType}}_Filter(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected []{{.BaseType}}
		filterFunc func({{.BaseType}}) bool
	}{
		{
			name: "starts with f",
			slc: []{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz"},
			expected: []{{.BaseType}}{"foo", "fizz"},
			filterFunc: func(s {{.BaseType}}) bool { return len(s) > 0 && s[0] == 'f' },
		},
		{
			name: "contains x",
			slc: []{{.BaseType}}{"max", "foo", "xray", "homer", "boxy", "blue"},
			expected: []{{.BaseType}}{"max", "xray", "boxy"},
			filterFunc: func(s {{.BaseType}}) bool {
				for i := 0; i < len(s); i++ {
					if s[i] == 'x' {
						return true
					}
				}
				return false
			},
		},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			result := {{.PackageType}}(tt.slc).Filter(tt.filterFunc).Value()
			if !reflect.DeepEqual(tt.expected, result) {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func Test{{.PackageType}}_Each(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store({{.BaseType}}({{.ZeroValue}}))

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected {{.BaseType}}
		eachFunc func({{.BaseType}})
	}{
		{
			name: "concat",
			slc: []{{.BaseType}}{"abc", "def", "ghi", "jkl", "mno", "pqr"},
			expected: "abcdefghijklmnopqr",
			eachFunc: func(n {{.BaseType}}) {
				v := rabbit.Load().({{.BaseType}})
				v  = v + n
				rabbit.Store(v)
			},
		},
		{
			name: "prepend",
			slc: []{{.BaseType}}{"aa", "bb", "cc", "dd", "ee"},
			expected: "eeddccbbaaabcdefghijklmnopqr",
			eachFunc: func(n {{.BaseType}}) {
				v := rabbit.Load().({{.BaseType}})
				v  = n + v
				rabbit.Store(v)
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			{{.PackageType}}(tt.slc).Each(tt.eachFunc)
			v := rabbit.Load().({{.BaseType}})
			if tt.expected != v {
				t.Errorf("expected %s, got %s", tt.expected, rabbit)
			}
		})
	}
}

func Test{{.PackageType}}_TryEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store({{.BaseType}}({{.ZeroValue}}))

	myErr := errors.New("i am an error")
	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected int
		expected2 error
		before func()
		eachFunc func({{.BaseType}}) error
	}{
		{
			name: "concat",
			slc: []{{.BaseType}}{"abc", "def", "ghi", "jkl", "mno", "pqr"},
			expected: NotInSlice,
			expected2: nil,
			eachFunc: func(n {{.BaseType}}) error {
				v := rabbit.Load().({{.BaseType}})
				v  = v + n
				rabbit.Store(v)
				return nil
			},
		},
		{
			name: "prepend",
			slc: []{{.BaseType}}{"aa", "bb", "cc", "dd", "ee"},
			expected: NotInSlice,
			expected2: nil,
			eachFunc: func(n {{.BaseType}}) error {
				v := rabbit.Load().({{.BaseType}})
				v  = n + v
				rabbit.Store(v)
				return nil
			},
		},
		{
			name: "errors",
			slc: []{{.BaseType}}{"aa", "bb", "cc", "dd", "ee"},
			expected: 3,
			expected2: myErr,
			before: func() { rabbit.Store({{.BaseType}}({{.ZeroValue}})) },
			eachFunc: func(n {{.BaseType}}) error {
				v := rabbit.Load().({{.BaseType}})
				if len(v) >= 6 {
					return myErr
				}
				v  = n + v
				rabbit.Store(v)
				return nil
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := {{.PackageType}}(tt.slc).TryEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func Test{{.PackageType}}_IfEach(t *testing.T) {
	t.Parallel()

	var rabbit atomic.Value
	rabbit.Store({{.BaseType}}({{.ZeroValue}}))

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected int
		expected2 bool
		before func()
		eachFunc func({{.BaseType}}) bool
	}{
		{
			name: "all return true",
			slc: []{{.BaseType}}{"aa", "bb", "cc", "dd", "ee"},
			expected: NotInSlice,
			expected2: true,
			eachFunc: func(n {{.BaseType}}) bool {
				v := rabbit.Load().({{.BaseType}})
				v  = v + n
				rabbit.Store(v)
                return true
			},
		},
		{
			name: "subtract n",
			slc: []{{.BaseType}}{"aa", "bb", "cc", "dd", "ee"},
			expected: NotInSlice,
			expected2: true,
			eachFunc: func(n {{.BaseType}}) bool {
				v := rabbit.Load().({{.BaseType}})
				v  = n + v
				rabbit.Store(v)
                return true
			},
		},
		{
			name: "breaking",
			slc: []{{.BaseType}}{"aa", "bb", "cc", "dd", "ee"},
			expected: 3,
			expected2: false,
			before: func() { rabbit.Store({{.BaseType}}({{.ZeroValue}})) },
			eachFunc: func(n {{.BaseType}}) bool {
				v := rabbit.Load().({{.BaseType}})
				if len(v) >= 6 {
					return false
				}
				v  = n + v
				rabbit.Store(v)
				return true
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			if tt.before != nil {
				tt.before()
			}
			e, i := {{.PackageType}}(tt.slc).IfEach(tt.eachFunc)
			if tt.expected != e {
				t.Errorf("expected %v, got %v", tt.expected, e)
			}
			if tt.expected2 != i {
				t.Errorf("expected %v, got %v", tt.expected2, i)
			}
		})
	}
}

func Test{{.PackageType}}_Map(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		slc []{{.BaseType}}
		expected []{{.BaseType}}
		mapFunc func({{.BaseType}}) {{.BaseType}}
	}{
		{
			name: "replace vowels",
			slc: []{{.BaseType}}{"cats", "dogs", "fish", "birds", "lizards", "mice"},
			expected: []{{.BaseType}}{"cXts", "dXgs", "fXsh", "bXrds", "lXzXrds", "mXcX"},
			mapFunc: func(n {{.BaseType}}) {{.BaseType}} {
				if strings.ContainsAny(n, "aeiou") {
					// hacky!
					n = strings.Replace(
							strings.Replace(
								strings.Replace(
									strings.Replace(
										strings.Replace(n, "a", "X", -1),
										"e", "X", -1,
									),
									"i", "X", -1,
								),
								"o", "X", -1,
							),
							"u", "X", -1,
						)
				}
				return n
			},
		},
		{
			name: "lowercase",
			slc: []{{.BaseType}}{"AbCdE", "aaa", "DDD", "ABx", "12AS"},
			expected: []{{.BaseType}}{"abcde", "aaa", "ddd", "abx", "12as"},
			mapFunc: strings.ToLower,
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			{{.PackageType}}(tt.slc).Map(tt.mapFunc)
			if !reflect.DeepEqual(tt.expected, tt.slc) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func Test{{.PackageType}}_Chunk(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		size int
		slc []{{.BaseType}}
		expected [][]{{.BaseType}}
	}{
		{
			name: "chunks of 2 no remainder",
			size: 2,
			slc: []{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz", "beez"},
			expected: [][]{{.BaseType}}{[]{{.BaseType}}{"foo", "bar"}, []{{.BaseType}}{"baz", "fizz"}, []{{.BaseType}}{"buzz", "beez"}},
		},
		{
			name: "chunks of 2 with remainder",
			size: 2,
			slc: []{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz", "beez", "booz"},
			expected: [][]{{.BaseType}}{[]{{.BaseType}}{"foo", "bar"}, []{{.BaseType}}{"baz", "fizz"}, []{{.BaseType}}{"buzz", "beez"}, []{{.BaseType}}{"booz"}},
		},
		{
			name: "chunks of 100",
			size: 100,
			slc: []{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz", "beez", "booz"},
			expected: [][]{{.BaseType}}{[]{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz", "beez", "booz"}},
		},
		{
			name: "chunks of 4",
			size: 4,
			slc: []{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz", "beez", "booz"},
			expected: [][]{{.BaseType}}{[]{{.BaseType}}{"foo", "bar", "baz", "fizz"}, []{{.BaseType}}{"buzz", "beez", "booz"}},
		},
		{
			name: "chunks of 5",
			size: 5,
			slc: []{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz", "beez", "booz"},
			expected: [][]{{.BaseType}}{[]{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz"}, []{{.BaseType}}{"beez", "booz"}},
		},
		{
			name: "empty slice",
			size: 5,
			slc: []{{.BaseType}}{},
			expected: [][]{{.BaseType}}{},
		},
		{
			name: "invalid chunk size",
			size: -1,
			slc: []{{.BaseType}}{"foo", "bar", "baz", "fizz", "buzz", "beez", "booz"},
			expected: [][]{{.BaseType}}{},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			out := {{.PackageType}}(tt.slc).Chunk(tt.size)
			if !reflect.DeepEqual(tt.expected, out) {
				t.Errorf("expected %v, got %v", tt.expected, tt.slc)
			}
		})
	}
}

func Benchmark{{.PackageType}}_IndexOf(b *testing.B) {
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).IndexOf("a")
			}
		})
	}
}

func Benchmark{{.PackageType}}_Contains(b *testing.B) {
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).Contains("a")
			}
		})
	}
}

func Benchmark{{.PackageType}}_SortAsc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).SortAsc()
			}
		})
	}
}

func Benchmark{{.PackageType}}_SortDesc(b *testing.B) {
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).SortDesc()
			}
		})
	}
}

func Benchmark{{.PackageType}}_Reverse(b *testing.B) {
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).Reverse()
			}
		})
	}
}

func Benchmark{{.PackageType}}_Filter(b *testing.B) {
	benchFunc := func(n {{.BaseType}}) bool {
		return true
	}
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).Filter(benchFunc)
			}
		})
	}
}

func Benchmark{{.PackageType}}_Each(b *testing.B) {
	benchFunc := func(n {{.BaseType}}) { n = {{.ZeroValue}} }
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).Each(benchFunc)
			}
		})
	}
}

func Benchmark{{.PackageType}}_Map(b *testing.B) {
	benchFunc := func(n {{.BaseType}}) {{.BaseType}} {
		return n
	}
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).Map(benchFunc)
			}
		})
	}
}

func Benchmark{{.PackageType}}_Unique(b *testing.B) {
	benchmarks := []struct {
		name string
		slc []{{.BaseType}}
	}{
		{
			name: "10 elements",
			slc: gen{{.PackageType}}(b, 10),
		},
		{
			name: "100 elements",
			slc: gen{{.PackageType}}(b, 100),
		},
		{
			name: "1000 elements",
			slc: gen{{.PackageType}}(b, 1000),
		},
		{
			name: "10000 elements",
			slc: gen{{.PackageType}}(b, 10000),
		},
		{
			name: "100000 elements",
			slc: gen{{.PackageType}}(b, 100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				{{.PackageType}}(bm.slc).Unique()
			}
		})
	}
}
